import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import SarnovaHeader from "@/components/SarnovaHeader";
import NavSidebar from "@/components/NavSidebar";
import Container from "@/components/Container";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sarnova Design System | Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased flex flex-col`}>
        <SarnovaHeader />
        <Container className="bg-blue-400 flex-1">
          <main>
            <NavSidebar />
            {children}
          </main>
        </Container>
      </body>
    </html>
  );
}
