import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import SarnovaHeader from "@/components/SarnovaHeader";


const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sarnova Design System | Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} antialiased`}
      >
        <SarnovaHeader />
        {children}
      </body>
    </html>
  );
}
