import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { BrandProvider } from "@/context/BrandContext";
import "./globals.css";
import SarnovaHeader from "@/components/SarnovaHeader";
import MobileNavSidebar from "@/components/MobileNavSidebar";
import Container from "@/components/Container";
import NavSidebar from "@/components/NavSidebar";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sarnova Design System | Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased flex flex-col`}>
        <BrandProvider>
          <SarnovaHeader />
          <Container className="flex-1">
            <main className="md:flex md:gap-8">
              <MobileNavSidebar />
              <NavSidebar />
              <div className="md:ml-72">
                {children}
              </div>
            </main>
          </Container>
        </BrandProvider>
      </body>
    </html>
  );
}
